#include <Windows.h>
#include <vector>
#include <cstring>
#include <cstdio>

#pragma warning(disable: 4996)

static std::vector<char*> g_injectedStrings;

char* InjectString(const char* str) {
    if (!str || str[0] == '\0')
        return nullptr;

    size_t len = strlen(str) + 1;

    char* buffer = (char*)VirtualAlloc(
        nullptr,
        len,
        MEM_COMMIT | MEM_RESERVE,
        PAGE_READWRITE
    );

    if (buffer) {
        memcpy(buffer, str, len);
        g_injectedStrings.push_back(buffer);
    }

    return buffer;
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved) {
    switch (ul_reason_for_call) {
    case DLL_PROCESS_ATTACH:
    {
        DisableThreadLibraryCalls(hModule);

        InjectString("elease\\AlterNative.pdb");
        InjectString("SERVER_INVITE_MSG");
        InjectString("FindIsGameUIActive: not");
        InjectString("AN_CHAT_INTERNAL_");
        InjectString("SearchDragonFireMem");
        InjectString("Menu/Aimbot - Fakelag");
        InjectString("Menu/Aimbot - Anti-Aimbot");
        InjectString("You are injected!");
        InjectString("reload;get_b67");
        InjectString("Removing detoured 'R_GLStudioDrawPoints'");
        InjectString("movement_strafe_hack_dir_auto");
        InjectString("strafe_hack_limit_velocity_max");
        InjectString("Shutting down cheat module subsystems...");
        InjectString("seconds until the dll is comple");
        InjectString("vk group: vk.com/alternativehack");
        InjectString("n invitation to the server you are currently o");
        InjectString("knifebot_predict_local_delta");
        InjectString("speedhack_active");
        InjectString("rainbow_route_line");
        InjectString("visual_player_dynamiclight_color_tt");
        InjectString("kz_strafe_psilent");
        InjectString(".knifebot.friendlyfire");
        InjectString("draw_fov.psilent.color.filled");
        InjectString("Suitable For KZ/HNS Game.");
        InjectString("Factor##edgebug");
        InjectString("VISUALS_GUI_COLOR_BUTTON_HOVERED");
        InjectString("m.block_attack_after_kill");
        InjectString("Another hook is already present while trying to hook");
        InjectString("aim.psilent.angle");
        InjectString("NorAdrenaline loaded");
        InjectString("esp_sound_minimum_volume");
        InjectString("Fake lag while shooting");
        InjectString("menu_legit_global_section");
        InjectString("XxharCs Multihack");
        InjectString("Wallhack %s");
        InjectString("BadReadPtr: PushEngstudioPointer");
        InjectString("Transparent Walls");
        InjectString("t.me/animstate");
        InjectString("t.me/chzxreverse");
        InjectString("t.me/sarcastroph3");
        InjectString("t.me/w1lliam1337");
        InjectString("-customtriggerbot");
        InjectString("K: %i - D: %i - HS: %i");
        InjectString("Inexinferis Revolution");
        InjectString("triggerbot.visible.check");
        InjectString("aimbot.fov.distance.based");
        InjectString("R8 by devr");
        InjectString("Project SobFoX");
        InjectString("https://cosmos.blagofm.ru/listen/blagofm/radio.mp3");
        InjectString("(P.s just shows, not turns off the content when you turn off this item)");
        InjectString("https://das-edge14-live365-dal02.cdnstream.com/a48122");
        InjectString("surf_helper.view_aligment.type_call_cursor_triggering");
        InjectString("Fastcupcheat Counter");
        InjectString("Name stealer interval");
        InjectString("Bunnyhop no touch ground illusion");
        InjectString("Perfect silent aim max. angle");
        InjectString("fastcup cheat by kacorvixon");
        InjectString("Predict future position for the");
        InjectString("Enter you search string here");
        InjectString("Bypass wallback blocker");
        InjectString("Bypass Wallback Blocker");
        InjectString("Recoil compensation (P/Y)");
        InjectString("Standalone recoil compensation");
        InjectString("Disable rendering of teammates");
        InjectString("Visual recoil adjustment");
        InjectString("OffButtonsIcon");
        InjectString("LGBTFlag");
        InjectString("\" invites to server \"");
        InjectString("RussianFlag");
        InjectString("Press INSERT for opening cheat menu.");
        InjectString("Create Script from Clipboard");
        InjectString("Show description of features");
        InjectString("Telegram channel 2: @colby");
        InjectString("knifebot_KEY_MOUSE5");
        InjectString("knifebot_bot_bypass");
        InjectString("knifebot_fixbox_s");
        InjectString("binary\\ragebot.ini");
        InjectString("GroundStrafe.StandUp.FallVelocity");
        InjectString("StrafeHelper.Correct.Limit.Smooth");
        InjectString("Cheat injected :3");
        InjectString(".penetration.minimum_damage");
        InjectString("mwheel.helper.up.insert_extra");
        InjectString("down.distributor.percent");
        InjectString("debug.print_in_game");
        InjectString("visuals.screen.textures");
        InjectString("press INSERT to open settings");
        InjectString("Нажмите INSERT для скрытия");
        InjectString("MOUSE4 or INSERT - enable/disable kb");
        InjectString("X@K 6au' qpJIeu'MTpoBep");
        InjectString("With love for Zippow. Don't suck, go win!");
        InjectString("Error #0005. Couldn't find g_pEngineMsgBase pointer.");
        InjectString("hpp forever | mark lotven");
        InjectString("On \"TAB\" you can reconnect.");
        InjectString("Player Kicker 2025 Successfully");
        InjectString("C:\\hack\\Release\\scroll_filter.pdb");
        InjectString("83 EC 4C C6 44 24 00 03 E8 ? ? ? ? D8 25");
        InjectString("56 8B F1 E8 ? ? ? ? C7 06");
        InjectString("0F BF 04 ? ? ? ? ? C3");
        InjectString("68 *? ? ? ? 8B 01 89 5C 24 ?");
        InjectString("8B 35 *? ? ? ? 8D 04 40");
        InjectString("Overlay##Bhop");
        InjectString("3 FOG: %i!%i (%.2f%%) { %i, %i, %i }");
        InjectString("Too fast scrolled bhops: %i (%.2f%%)");
        InjectString("NOT_HPP\\bin\\NOT_HPP.pdb");
        InjectString("Knife_Helper\\src\\gui\\");
        InjectString("CSvcHook::setCallback: Message %d is already detoured");
        InjectString("Don't be a loser, buy MIDNIGHT");
        InjectString("Subscribe to t.me/dankm3m3");
        InjectString("!etaprogamojetvsesykableatzaebalOS mode.");
        InjectString("cs16_frame_skip\\Release\\cs16_frame_skip.pdb");
        InjectString("Distance: %.0f Maxspeed: %.0f Prestrafe: %.0f Strafes: %i FPS: %i");
        InjectString("xHancer\\Release\\xHancer.pdb");
        InjectString("Coded by yahowha");
        InjectString("Channel: youtube.com/c/Sayuri7Mad");
        InjectString("*** Crosshair edit by Freya");
        InjectString("> Unloading (wait 3sec)...");
        InjectString("crosshair\\Release\\crosshair.pdb");
        InjectString("Private hack by d-_-b");
        InjectString("Frames to ground : %d");
        InjectString("hack/by d-_-b/");
        InjectString("\\MouseWheel.pdb");
        InjectString("Ideal Bhops Percentage: %f");
        InjectString("PushID/PopID or TreeNode/TreePop Mismatch!");
        InjectString("Forgot to call Render() or EndFrame()");
        InjectString("g.Style.Alpha >= 0.0f && g.Style.Alpha <= 1.0f");
        InjectString("Need a positive DeltaTime (zero");
        InjectString("\\Release\\SultanHack.pdb");
        InjectString("\\Debug\\SultanHack.pdb");
        InjectString("You cannot update a currently in procecss window");
        InjectString("Enabled View model changer");
        InjectString("Activate with knife and C4 only");
        InjectString("Optimizer LJ Mode");
        InjectString("Aim/shoot through smoke");
        InjectString("Release\\FluidAim_v3.pdb");
        InjectString("55 8B EC 56 8B F1 33 C0 57 8B 7D 08");
        InjectString("Hide Everything in OBS Ga");
        InjectString("AntiAimExample.lua");
        InjectString("recoil_compensation_after_shots_fired");
        InjectString("kz_jump_bug_slow_speed");
        InjectString("PlayerMove: not found.");
        InjectString("Tweak bar module has not been terminated properly: call TwTerminate()");
        InjectString("Initiating Turbo Badger - version %s");
        InjectString("TBNodeRefTree::ResolveNode - No tree found for request");
        InjectString("Plugins support disabled, rebuild MyGUI without MYGUI_DISABLE_PLUGINS");
        InjectString("Child ButtonExpandCollapse not found in skin (TreeControlItem must have ButtonExpandCollapse)");
        InjectString("fps_boost_use_config");
        InjectString("bhop_standup_fallingspeed");
        InjectString("Ground angle: %.1f");
        InjectString("pfx#max_flash");
        InjectString("[ADetect] Hide file");
        InjectString("Add here files you want to inject automatically");
        InjectString("<value | random | disable>");
        InjectString("XGuardMutex%i");
        InjectString("emulator, generated SteamID:");
        InjectString("global-disable-aimbot");
        InjectString("main-mouse-impact-desc");
        InjectString("kreedz-global-");
        InjectString("midnight-gui-");
        InjectString("%s = turn on/off cheat");
        InjectString("espfontshadow");
        InjectString("drawaimsize");
        InjectString("default.aimbot.targeting.randomize");
        InjectString("settings.triggerbot.active");
        InjectString("www.csxr.ru");
        InjectString("aim_DrawMinDistance");
        InjectString("Aimbot loaded successfully");
        InjectString("rem_RemoveFlash");
        InjectString("stand_aim_z");
        InjectString("aimbot_z_stand");
        InjectString("[ESLWire]");
        InjectString(".ini nicht gefunden!");
        InjectString("unbind UPARROW; unbind LEFTARROW; unbind RIGHTARROW; unbind D");
        InjectString("aimbot.visible.check");
        InjectString("misc.draw.punchangle");
        InjectString("Aimbot.Visible.Check");
        InjectString("aim.distance.based.delta");
        InjectString("esp.triggerbot.area");
        InjectString("\"Text\":\"Aimbot\"");
        InjectString("[E8 *? ? ? ?] 83 C4 04 8B 0D ? ? ? ? 46");
        InjectString("[E8 * ? ? ? ? ] 83 C4 04 8B 86 ? ? ? ? 43");
        InjectString("[visit: csxr.ru]");
        InjectString("33 DB 89 35 *? ? ? ?");
        InjectString("bind i \"exec killsay.cfg\"");
        InjectString("exit_the_hack");
        InjectString("\\Release\\DllHack.pdb");
        InjectString("Key used to activate the aim");
        InjectString("Open/Close the hack men");
        InjectString("use the console to modify a cheat");
        InjectString("[One Winged Angel]");
        InjectString("Password Denied!!! (%4.1f)");
        InjectString("Press F12 to disable cheat");
        InjectString("Kuvik Hook v");
        InjectString("Bind this to key for StandUp Groundstrafe");
        InjectString("Sets knifebot's attack distance");
        InjectString("Hack built by CSHackCreator");
        InjectString("\\Release\\DllStub.pdb");
        InjectString("\\CSHackCreator-2-Demo\\");
        InjectString("blend_yaw: my: %i != orig: %i");
        InjectString("\\Release\\SimpleBaseDLL.pdb");
        InjectString("fakelag_in_air");
        InjectString("aim at the push of the left button");
        InjectString("weapon models through wall");
        InjectString("Remove the flashbang");
        InjectString("luno free\\Release\\base.pdb");
        InjectString("No FOV pattern found");
        InjectString("Silent Aim Preference");
        InjectString("Aim Through Wall");
        InjectString("wall_xqzhack");
        InjectString("//Aimbot Settings");
        InjectString("Anti-Smoke & Anti-Flash");
        InjectString("Couldn't Read From Opengl32.dll Address");
        InjectString("Couldn't Get Proccess Info");
        InjectString("Maybe your OpenGL driver is not compatible");
        InjectString("Couldn't Get TEB From Opengl32.");
        InjectString("KRAGE Hack loaded");
        InjectString("Disable FPS Boost feature.");
        InjectString("##Hitbox##aimbot");
        InjectString("##Active model___");
        InjectString("its triggers to activate aim assist");
        InjectString("norecoil_value 1");
        InjectString("dwSendPacket: not found");
        InjectString("These commands can significantly affect");
        InjectString("To combine multiple commands into one");
        InjectString("ithubusercontent.com/Squizoff");
        InjectString("ithubusercontent.com/squizoff");
        InjectString("Randomize SteamID");
        InjectString("Aimbot Demochecker Bypass");
        InjectString("Silent ##Knifebot");
        InjectString("aim_recoil_standalone_compensation_after_shots_fir");
        InjectString("EnableSteamIDSpoof");
        InjectString("Command_Name_Parser_CreateSteam");
        InjectString("BlockForwardToServerBy_CLIENT_LIST");
        InjectString("SuccessFul load steam");
        InjectString("TFormatSteamReturnX");
        InjectString("Happy monday!");
        InjectString("Nov 6 2020, 00:59:26 (stable)");
        InjectString("Happy friday!");
        InjectString("Happy wednesday!");
        InjectString("You sure quit hack?");
        InjectString("enable hack again press");
        InjectString("unloading dll..");
        InjectString("Jun 19 2020, 14:58:57 (stable)");
        InjectString("ragColor.rgb = mix(fragColor.rgb, vec3(rand(vec2(uv.y * time))), noise * 0.3).rgb");
        InjectString("ay\\src\\CSectionData.cpp");
        InjectString("Can't found file! Usage: bnm_load");
        InjectString("//fragColor.b = mix(fragColor.r, texture(iChannel0, vec2(xpos - nois");
        InjectString("minihook-ng\\Release\\test.pdb");
        InjectString("Blitzkrieg Bop v");
        InjectString("bb_d_perfectrow_stop");
        InjectString("Done shit with interfaces");
        InjectString("E8 ?? ?? ?? ?? EB 36 8B 43 10");
        InjectString(".m_use_backtrack");
        InjectString("g_hotkeys->no_spread");
        InjectString("Remove Visual Recoil");
        InjectString("Enable Sky Color Changer");
        InjectString("FF 15 ?? ?? ?? ?? 68 ?? ?? ?? ?? E8 ?? ?? ?? ?? 83 C4 1C");
        InjectString("FF 15 ?? ?? ?? ?? 83 C4 04 89 87 18 77 01 00");
        InjectString("ESP Enabled##Visuals");
        InjectString("selected_session_bhop");
        InjectString("Can't register variable ``, already defined");
        InjectString("Couldn't find SpeedPtr pointer");
        InjectString("Cmd_AddCommand: clearplayers already defined");
        InjectString("Couldn't find EngineStudioPtr");
        InjectString("R_PARSE_SERVERNA");
        InjectString("Ziktor Markelov BEST");
        InjectString("AppData\\Roaming\\AlterNative Hack");
        InjectString("Enable##PSilent");
        InjectString("Couldn't find patch pattern 2 at Patch_Cmd_Alias.");
        InjectString("There is a timeout for pressing the button, please wait");
        InjectString("EMPTY_OR_NO_NICKNAME");
        InjectString(": \"BAD_NICKNAME\"");
        InjectString("##change_language");
        InjectString("CheckGameDirHash2");
        InjectString("../readme.txt");
        InjectString("02eb483d");
        InjectString("[Extra Mirror] Start CheckFileList:");
        InjectString("bluedots_large_png.vtex\"); background-size: auto 390px; background-img-opacity");
        InjectString("80 B9 ? ? ? ? 00 74 ? 48 8D 0D");
        InjectString("89 ? ? ? ? ? C6 ? ? ? ? ? ? 48 89 ? ? ? ? ? E8 ? ? ? ? 48");
        InjectString("D9 ? ? C7 81 ? ? ? ? 00 00 00 00 48 8D 15");
        InjectString("Shoot %s in %s from %s (mode: %s)");
        InjectString("Valthrun Overlay");
        InjectString("Valthrun Version");
        InjectString("audio_radar_enabled");
        InjectString("Disable GUI Menu(Eff");
        InjectString("It will fire after the delay even if");
        InjectString("aim_triggerbotkeyactive");
        InjectString("esp_entitywallhack");
        InjectString("misc_antihlguard");
        InjectString("No Visual Recoil");
        InjectString("net/wurstclient/Category");
        InjectString("Wurst Wurst Wurst!");
        InjectString("https://www.wurstclient.net/wurst7issues/");
        InjectString("net/wurstclient/hacks");
        InjectString("Button##aim");
        InjectString("\\Release\\Zero.pdb");
        InjectString("Only Blocks & Projectiles");
        InjectString("Left Button To Aim");
        InjectString("Yaw Randomness");
        InjectString("Toggle Aim Assist");
        InjectString("fusion internal |");
        InjectString("org/xjomama/doritos");
        InjectString("xjomama/doritos/b");
        InjectString("Removes the cheat from the game.");
        InjectString("[%sHorion%s] %sCheat");
        InjectString("Download: horionclient.tk");
        InjectString("40 53 56 57 48 81 EC ?? ?? ?? ?? 48 C7 44");
        InjectString("4C 8B DC 55 53 49 8D 6B ?? 48 81 EC ?? ??");
        InjectString("48 89 5C 24 ?? 48 89 6C 24 ?? 48 89 74 24");
        InjectString("FF 50 08 4C 8D 05");
        InjectString("F3 ?? ?? ?? ?? ?? ?? ?? 41 0F 2F");
        InjectString("48 8D 0D ?? ?? ?? ?? 89 1C 81");
        InjectString("48 89 5C 24 10 57 48 83 EC ?? 0F 29");
        InjectString("40 53 48 83 EC ?? 48 8B DA 8B 52 ?? 85");
        InjectString("40 57 48 83 EC ?? 48 C7 44 24 ?? FE FF");
        InjectString("40 55 53 56 57 41 54 41 55 41 56 41 57");
        InjectString("48 8D 05 ?? ?? ?? ?? 48 89 01 48 8B");
        InjectString("2F 48 85 DB ?? 2A F3");
        InjectString("EB 18 F3 0F 10 05 ?? ?? ?? ?? 44 0F");
        InjectString("4C 8B F8 48 8B 0D ?? ?? ?? ?? 48 8B");
        InjectString("48 8B C4 55 48 8D 68 ?? 48 81 EC ??");
        InjectString("40 57 48 83 EC 20 48 83 B9 ?? ?? ??");
        InjectString("CC 8B 41 ?? 89 41 ?? C3");
        InjectString("48 83 EC ?? 80 B9 ?? ??");
        InjectString("40 53 48 83 EC 20 48 8B D9 E8 ??");
        InjectString("48 89 5C 24 08 57 48 ?? ?? ?? ??");
        InjectString("40 53 48 83 EC ?? 0F 29 74 24 ??");
        InjectString("48 8D 05 ?? ?? ?? ?? 48 89");
        InjectString("40 57 48 ?? ?? ?? ?? ?? ?? 48 ?? ??");
        InjectString("41 80 BF ?? ?? ?? ?? 00 0F 85 ?? ??");
        InjectString("minecraft/kalkonclient/languag");
        InjectString("minecraft/kalkonclient/multi");
        InjectString("client/gui/LoliGuiManager");
        InjectString("client/main/Loli.class");
        InjectString("client/modules/Xray.class");
        InjectString("utils/XrayUtils.clas");
        InjectString("net/minecraft/src/iHack.class");
        InjectString("baritone/BaritoneProvider.class");
        InjectString("baritone/aa.class");
        InjectString("net/impactclient/0rt.class");
        InjectString("hook/mixin/plugin/Impact");
        InjectString("inertia/logos/bottom");
        InjectString("inertia/AEuc.class");
        InjectString("/inertia/filemanager/folder");
        InjectString("/inertiatextatlas.png");
        InjectString("Launching Nursultan Client");
        InjectString("Ваша подписка вот-вот з");
        InjectString("minecraft/expensive/fonts/");
        InjectString("expensive/images/button");
        InjectString("expensive/sounds/bubble");
        InjectString("assets/nursultan/PK");
        InjectString("nursultan/cape/PK");
        InjectString("/cape/premium_cape.png");
        InjectString("/icons/mainmenu/vk.png");
        InjectString("assets/minecraft/wexside");
        InjectString("/season/utils/shader");
        InjectString("fcked/by/regullar/");
        InjectString("gui/components/builder/");
        InjectString("clickgui/components/settings");
        InjectString("clickgui/comp/CheckBox");
        InjectString("settings/MultiBoxComponent");
        InjectString("atoll/gui/setting/");
        InjectString("Max Mining Delay");
        InjectString("§b[Atoll] §a");
        InjectString("Starting to mine block at");
        InjectString("assets/hypixelcry/logo.png");
        InjectString("features/macros/GhostBlocks.class");
        InjectString("/impl/modules/render/");
        InjectString("/impl/modules/movement/InventoryMove");
        InjectString("/impl/modules/combat/BowRelease");
        InjectString("Automatically places and explodes beds in the nether or end for combat");
        InjectString("/aristois/config/transformer/m/Dispatcher");
        InjectString("Aristois has been updated to");
        InjectString("me.deftware.aristois.config");
        InjectString("hack/command/commands/CmdGamemode");
        InjectString("hack.module.mods.Nofall");
        InjectString("hack.module.mods.AutoSteal");
        InjectString("adjustable alpha level for non-xray blocks");
        InjectString("lean/sounds/config-load.");
        InjectString("catlean/mixins/cli");
        InjectString(".catlean.api.event");
        InjectString(".api.event.events.render.FrameBufferEvent");
        InjectString("com/krazzzzymonkey/catalyst");
        InjectString("/modules/combat/KillAura/");
        InjectString("/modules/render/XRay");
        InjectString("/modules/combat/AutoCrysta");
        InjectString("/texture/mainmenu/clickgui.png");
        InjectString("Injecting with IFMLLoadingPlugin.");
        InjectString("/modules/combat/Aimbot");
        InjectString("Aimbot (otheritems & gravitytype)");
        InjectString("fluger/image/combat.png");
        InjectString("fluger/image/visual.png");
        InjectString("/assets/minecraft/fluger/");
        InjectString("sodium/shaders/opacity_xray");
        InjectString("/changelog/JexChangelog");
        InjectString("/dustin/jex/JexClient.class");
        InjectString("/impl/combat/killaura/KillAur");
        InjectString("lambda/mixin/entity/MixinEntit");
        InjectString("/lambda/shadow/kotlin/");
        InjectString("resources/liquidbounce/glow.png");
        InjectString("/liquidbounce/features/module/");
        InjectString("trumpclientftw_bape_ggA");
        InjectString("trumpclientftw_vape_ggA.class");
        InjectString("Smoothly aims to close range targets");
        InjectString("AutoClicker Automatically clicks for you while holding down the attack button");
        InjectString("Draws arrows to players outside of your field of view");
        InjectString("FakeLag Delays packets, simulating lag");
        InjectString("MLG Automatically places water under you if you fall");
        InjectString("Removes the click delay that normally occurs after missing an attack");
        InjectString("Macros let you set a macro for items to quickly swap to on your hotbar");
        InjectString("Lags you at certain times to increase attack distance");
        InjectString("\"knifebot.key\"");
        InjectString("up.distribution_chance");
        InjectString("knifebot.ignore_bot");
        InjectString("player_esp.teammates");
        InjectString("STR-helper");
        InjectString("] - Leftward strafe");
        InjectString("] - Groundstrafe");
        InjectString("\\BaseHook-HLMods.pdb");
        InjectString("mwheel.down.distributor");
        InjectString("0F BF 04 95 ?? ?? ?? ?? C3");
        InjectString("\\OrionProject\\I");
        InjectString("\\Interium CS 1.6\\");
        InjectString(".dont_shoot_on_invisible");
        InjectString("Bunnyhop\\Release\\Bunnyhop.pdb");
        InjectString("Bunnyflop v1 by");
        InjectString("Bunnyflop v2 by");
        InjectString("7 - SmartSteamEmu");
        InjectString("\\interception.pdb");
        InjectString("\\\\.\\interception00");
        InjectString("I'm glad you're using my cheat!");
        InjectString("##KnifebotSwapAttackKey");
        InjectString("Scripts/Name stealer/");
        InjectString("Flash: %.0f%%");
        InjectString("sf_showfps_onconsole");
        InjectString("hide_triangles_transparent");
        InjectString("Fl : %.0f%%");
        InjectString("aim_triggerbot_delay");
        InjectString("other.recoil");
        InjectString("galil.recoil");
        InjectString("visuals_off_after_death");
        InjectString("knifebot_distance_script_leave");
        InjectString("fc_autorun.cfg has been loaded");
        InjectString("bhop_wog_skip_frame_gt");
        InjectString("strafe_helper_trainer_fadespeed");
        InjectString("Details of your own build");
        InjectString("BHOP_SCROLL_INTERVALS");
        InjectString("BHOP_WOG_SKIP_FRAME");
        InjectString("STRAFE_HELPER_FILTER");
        InjectString("Override while scoped");
        InjectString("Unloading Not_Hpp");
        InjectString("Advanced##Bhop");
        InjectString("Works only in the steam client.");
        InjectString("Connect delay (sec)");
        InjectString("Chat spam type");
        InjectString("say_radiospam");
        InjectString("GhettoVecDodger");
        InjectString("L3g3nd4ri 4m1r");
        InjectString("7h1rd P3rs0n");
        InjectString("/[sYn]3rdPerson.txt");
        InjectString("Removing OpenGL hooks..");
        InjectString("aim_DrawMinDistance");
        InjectString("aim_HideWpnEvent");
        InjectString("aim_hidewpnevent");
        InjectString("%i%% flashed");
        InjectString("Contact: Xikwri Neyrra");
        InjectString("Coded by Xikwri Neyrra");
        InjectString("Release\\flautist.pdb");
        InjectString("\\cheat related stuff");
        InjectString("HookThread: Could not get segment");
        InjectString("Could not get export table address");
        InjectString("HookExport: Returned false");
        InjectString("DllMain: Failed to create hook");
        InjectString("AIM CFG for Steam / NonSteam");
        InjectString("L33T XTREME HEADSHOT ACTIVATED");
        InjectString("Scripts/Aim for Steam/NonSteam");
        InjectString("Trigger.FriendlyFire");
        InjectString(".BulletTwoSmooth");
        InjectString("Draw Fov Trigger");
        InjectString("Other.FlashStatus");
        InjectString("Burst Fire Disabled");
        InjectString("Bloo's cheat script v");
        InjectString("| lower recoil - no lookdown");
        InjectString("X/l!0ush5=f)&(b/:$> &:z$\"4<)u9%;");
        InjectString("Kotan.beyy Hack Aktif");
        InjectString("|Key.Panic");
        InjectString("Couldn't find SpeedPtr pointer");
        InjectString("[MemSearch] WARNING: Using SIZE_STATIC for CLSize");
        InjectString("Couldn't find scanning pattern for ^engine_studio_api_t");
        InjectString("You should try injecting this cheat");
        InjectString("SearchMemOrder");
        InjectString("GetAsyncKeyState");
        InjectString("USER32.dll");
        InjectString("glColor4f");
        InjectString("glBlendFunc");
        InjectString("2;2@2E2J2R2X2^2d2j2p2v2|2");
        InjectString("Ku@Eso>9W1");
        InjectString("DP2.F32 R1.x, R0, {0.211324871, 0, 0, 0}.x;");
        InjectString("pB8accV8Cbgva253VhREPw==");
        InjectString("// aim while shooting, as in HLH");
        InjectString("wglGetCurrentDC o glGetFloatv OPENGL32.dll S DeleteObject");
        InjectString("license-success-ok-");
        InjectString("gate.php?serial=");
        InjectString("glColor4ub");
        InjectString("glPushMatrix");
        InjectString("glPopAttrib");
        InjectString("wglGetCurrentDC");
        InjectString("fakelag_stop_on_attack");
        InjectString("jumpbug_auto_damage");
        InjectString("Spam System Commands:");
        InjectString("Bypass KB Detector");
        InjectString("CL_HookEvent");
        InjectString("glVertex2d");
        InjectString("Stdio (lujiangz)");
        InjectString("lujiangz config LOADED...");
        InjectString("ciaey installing hooks...");
        InjectString("settings automatically saved.");
        InjectString("free library...");
        InjectString("ciaey deleting hooks");
        InjectString("SkiLl Cfg ACTIVATE");
        InjectString("FDAS)(&*^\"&^%^$ by uNk");
        InjectString("MPH Leis Release");
        InjectString("antiwallbang=0");
        InjectString("antiwallbang=1");
        InjectString("// configurations... loaded");
        InjectString("burst_knife \"shoot 0");
        InjectString("GetKeyState");
        InjectString("glPolygonMode");
        InjectString("wglGetCurrentContext");
        InjectString("play AHK_PlayMe");
        InjectString("Script info will not be sh");
        InjectString(".exe.bat.com.cmd.hta");
        InjectString("#MaxThreadsPerHotkey");
        InjectString("has been injected!");
        InjectString("Author: th3fla");
        InjectString("lambda at lua/lua_cvar.cpp");
        InjectString("at lua/lua_cvar.cpp:");
        InjectString("at lua/lua_utlvector.cpp:");
        InjectString("MAD.F32 result_color0.xyz, R1, c[5].x, R0;");
        InjectString("Counter-Strike/KNIFEBOT_");
        InjectString("GetTextExtentPointA");
        InjectString("SelectObject");
        InjectString("CreateFontA");
        InjectString("glPopMatrix");
        InjectString("Press DEL button to close cheat");
        InjectString("TriggerBot + PSilent DLL");
        InjectString("Vac Status: UNDETECTED");
        InjectString("triggerdll\\Release\\");
        InjectString("Counter-Strike/#1_");
        InjectString("Counter-Strike/#8_");
        InjectString("visuals preview_C");
        InjectString("visuals preview_B");
        InjectString("#uhtj^stordqjo");
        InjectString("I`tg!!1wga84f780");
        InjectString("cx!Kfn]btsshld]nwds");
        InjectString("Tdsufq!=!bnc!!");
        InjectString("R0, {0.227027029, 0, 0, 0}.x");
        InjectString("NoSmoke percentage");
        InjectString("disable steamid spoof");
        InjectString("Karaulova POT E6");
        InjectString("55 8B EC 83 EC 08 A1 ? ? ? ? 56 33 F6 85 C0");
        InjectString("free library finished...");
        InjectString("build(%i) is not supported!");
        InjectString("0123456789ABCDEF");
        InjectString("wglSwapBuffers");
        InjectString("opengl32.dll");
        InjectString("Vector Aim\" \"vecing\"");
        InjectString("Multi Weapon Vec");
        InjectString("\" \" \"norecoil:medium\" \"recoil");
        InjectString("smokegrenade 1 999 1 0 0");
        InjectString("movement_strafe_hack_allow_on_surf");
        InjectString("Displays movement-related information");
        InjectString("Enables strafe accumulation when on ground");
        InjectString("Maximum velocity to speed up to");
        InjectString("glClearColor");
        InjectString("MSVCRT.dll");
        InjectString("glAlphaFunc");
        InjectString("Aiming: HEADSHOT DELUXE");
        InjectString("[ sIg ] h3AdSh0t ||[--");
        InjectString("Aiming: ULTIMATE HEADSHOT");
        InjectString("aimhelpcolor 100 255");
        InjectString("Remove the flashbang's");
        InjectString("before the aimbot is active");
        InjectString("= always aims when shooting");
        InjectString("FOV aktiviert / deaktiviert");
        InjectString("1 = Generate an AVSMP ticket");
        InjectString("_steamid_spoofer <");
        InjectString("Use the custom SteamID");
        InjectString("\\ExtraMirror-SteamID.pdb");
        InjectString("Изменять угол от");
        InjectString("Текущий конфиг:");
        InjectString("http:://guns.lol/hpp_forever");
        InjectString("Все видят нацеливание");
        InjectString("The procedure entry point %s could not be located in the dynamic link library %s");
        InjectString(";bAll;aim 1;shoot 1");
        InjectString("HS-Percentage : %4.1f");
        InjectString("alias Nickchangerr1 Nickchanger1;s");
        InjectString("&wNOTICE: &r OpenGL Is NOT Hooked");
        InjectString("2.000000 4000.000000 0.010000 0.000000");
        InjectString("[CDHack] Hey! It's me");
        InjectString("Strange server activity! Better leave.");
        InjectString("Ah... that secret handshake! :)");
        InjectString("walltrans 0.2;VacBursts;");
        InjectString("speed 1;Nickchanger_OFF");
        InjectString("if hasno deagle if money>= 500 #deagle;#secammo;");
        InjectString("alias nospeed unbspdm2");
        InjectString("if you want your name to change to random");
        InjectString("[Namejacker/Spam Off]");
        InjectString("[Radiospam Off]");
        InjectString("wallsensitivity=1");
        InjectString("hitboxaim 0;alias hitbox");
        InjectString("invFuriousGun;aimfirstpoint 0");
        InjectString("Grabbing engine funcs and setting up stuff");
        InjectString("Headshots: %d [%4.1f%%]");
        InjectString("aimsmoother=1");
        InjectString("Release\\oglBaseHook.pdb");
        InjectString("weaponesp=0");
        InjectString("20.85 6.65 2.85 d 5.35 5.35 2.84");
        InjectString("FarEsp 1 2500");
        InjectString("расставить_точки_над_и=1");
        InjectString("кнопка_нацеливани");
        InjectString("\\ЧитерБитер.pdb");
        InjectString("GetPrivateProfileStringA");
        InjectString("HeapCreate");
        InjectString("GetModuleFileNameA");
        InjectString("PRIVMSG NickServ :GHOST %s %s");
        InjectString("Dpoofdujpo!up!uif!tfswfs!ibt!cffo!mptu/");
        InjectString("!.!sfnfncfs!uijt!gps!mbufs!vtf/");
        InjectString("Zpv(sf!bmsfbez!dpoofdujoh!up!uif!tfs");
        InjectString("er_esp.enemies");
        InjectString("---------\": true");
        InjectString("lllllllllll\": false");
        InjectString("llllllllll\": 32");
        InjectString("lstrcmpiA");
        InjectString("KERNEL32.dll");
        InjectString("MessageBoxA");
        InjectString("paid-privatka by Garey");
        InjectString("KB work only CT");
        InjectString("NSD Prestrafe Correction");
        InjectString("auto_sbj_distance");
        InjectString("XGuard started at");
        InjectString("SteamID changer has been");
        InjectString("cl_pc;wait;wait;wait;snapshot;");
        InjectString("ClearScreenShots :3");
        InjectString("Aimbot_CorrectionEnabled");
        InjectString("Aimbot_ExactSetValue");
        InjectString("Visuals_Copyright");
        InjectString("ESPDot_ColorR");
        InjectString("BunnyHop_Enabled");
        InjectString("Couldn't find \"ScreenFade\"");
        InjectString("1 = Chest -> Head");
        InjectString("BunnyHop: %s");
        InjectString("Player %d not found..");
        InjectString("Smooth: %2.2f");
        InjectString("misc_FlashMessage");
        InjectString("esp_DrawTrigger");
        InjectString("trigger_OnlyZoom");
        InjectString("BulletTwoClampType");
        InjectString("Goto Freeze Time:");
        InjectString("Trigger ProSpread");
        InjectString("VirtualProtect");
        InjectString("DisableThreadLibraryCalls");
        InjectString("Name: aimkey");
        InjectString("sniperchest=1");
        InjectString("knifebot_dist");
        InjectString("knifebot_attack");
        InjectString("knifebot");
        InjectString("nospread_visrecoil=");
        InjectString("Aiming ON (All-Headshots)");
        InjectString("Aim Vectors\" { // aiming");
        InjectString("sir aim 2 shot");
        InjectString("trigger_Key */");
        InjectString("aim_TriggerHeadOnly");
        InjectString("esp_WHBlocker");
        InjectString("hyperbola - distance is devided");
        InjectString("auto fire area 4-20");
        InjectString("wallhack mode 0-6");
        InjectString("//NukedX New Master Recoil");
        InjectString("+@spread;@w;+attack");
        InjectString("R-Aimbot v1.0");
        InjectString("Wt\\R-Aimbot");
        InjectString("\\missing-name\\");
        InjectString("OpenGL Initialized (glBegin");
        InjectString("KREEDZ_BUNNYHOP_SCROLL_HELPER");
        InjectString("deagle.aim.psilent");
        InjectString("aimbot)_On knife");
        InjectString("BUNNYHOP_SCROLL_EMULATION");
        InjectString("##Menu/##Controls_");
        InjectString("_SH Legit");
        InjectString("cellaneous(Miscellaneous)");
        InjectString("Version=210&PlayerIp=");
        InjectString("loopx <name> executes name_x<name>");
        InjectString("?BATUREIS ELIT V2");
        InjectString("Thanks XSeA & Thanks");
        InjectString("##KeyAssignment##");
        InjectString("Assignment##Knifebot");
        InjectString("##Miscellaneous_Other");
        InjectString("##Duckhelp");
        InjectString("Version=139&PlayerIp=");
        InjectString("Version=141&PlayerIp=");
        InjectString("Version=143&PlayerIp=");
        InjectString("Version=145&PlayerIp=");
        InjectString("##Kzboost");
        InjectString("febot Distance Sta");
        InjectString("{\"status\":\"Success\",\"user\":\"");
        InjectString("Drun 3Fog Random");
        InjectString("- Teleport and play");
        InjectString("Teleport and record");
        InjectString("TeamLambert=1");
        InjectString("FUNGUN BYPASS BY");
        InjectString("KN1F3BOT by brrr^");
        InjectString("Config##Cfg");
        InjectString("if (floor(mod(fragCoord.y * 0.25, 2.0)) == 0.0)");
        InjectString("m *= 1.79284291400159 - 0.85373472095314 * ( a0*a0 + h*h )");
        InjectString("i1.x = step( x0.y, x0.x ); // x0.x > x0.y ? 1.0 : 0.0");
        InjectString("xHack_xtd @Mega.lol");
        InjectString("DrawAimspot=1");
        InjectString("alias FastStrafe \"alias yawspeed");
        InjectString("alias +Mega.lol \"-");
        InjectString("aim 1;#wait;#+attack");
        InjectString(";nospread 2;");
        InjectString("avadd 0 1.64 0.25 -0.05");
        InjectString("\" \"just aim\" \"aim 1");
        InjectString("\" \" \">BURSTMODE\" {");
        InjectString("\" \" \"g0d Supreme\" \"SI");
        InjectString("\" \" \"aim&shoot\" \"a");
        InjectString("Head\" \"xhackhead\"");
        InjectString(": deactivated");
        InjectString("/*if (texture(visualLayerSampler, fragUV).rgb != vec3(0.0)) {");
        InjectString("// GSAIM FOR DEAGLE");
        InjectString("DEAG1; DEAG2; DEAG3; DEAG4");
        InjectString("avadd 3 20.25 9.5");
        InjectString("ESPDot_VisibleEnabled");
        InjectString("setburst mac10");
        InjectString("setburst smokegrenade");
        InjectString("\">AIMBOT\" {");
        InjectString("aim 1;shoot 0");
        InjectString("Bind | Replay");
        InjectString("##Miscellaneous(Miscellaneous)");
        InjectString("&ServerName=");
        InjectString("&SteamId=7");
        InjectString("> %s: FreeLibraryAndExitThread.");
        InjectString("##LegitBot(");
        InjectString(".trigger.penetration");
        InjectString("%s: failed to unhook %s");
        InjectString("&ServerIpAdress=");
        InjectString("27015&PlayerName");
        InjectString("\",\"engine\":\"0x");
        InjectString("\",\"client\":\"0x");
        InjectString("Custom crosshair loaded! :3");
        InjectString("CrosshairColor [Open]");
        InjectString(";weapon 0;cl_bobcycle 0;");
        InjectString("esp 0;info 0;tglow 0;");
        InjectString("recoil 0;jump 0;duck 0;");
        InjectString("SteamChanger = True");
        InjectString("Disable aimbot when flashed");
        InjectString(".m_name.m_enable");
        InjectString(".m_remove_flashlight");
        InjectString("[-] Failed to find pattern: %s");
        InjectString("en1gma-tech\\settings\\");
        InjectString("48 8B 05 ?? ?? ?? ?? FF D0 E9 60 01 00 00");
        InjectString("48 8B 0D ?? ?? ?? ?? 48 8B 01 FF 50 ?? 8B DF");
        InjectString("E8 ?? ?? ?? ?? F3 0F 10 44 24 ?? 8B 4C 24 40");
        InjectString("_CHATOBJ1_");
        InjectString("__CHATOBJ001");
        InjectString("CHATOBJ3_SO");
        InjectString("CHATOBJ2_SO");
        InjectString("Release\\Crianosfera.pdb");
        InjectString("shld$qcfe)%+=#W`ec2gqt{759(5^rjw");
        InjectString("Couldn't Get TEB From Opengl32.dll");
        InjectString("Running the Game in OpenGl Mode..");
        InjectString("Can't Get OpenGL Version...");
        InjectString("Create & Save New");
        InjectString("Vermillion Hack Menu");
        InjectString("Vermillion [PUBLIC VERSION]");
        InjectString("by _or_75 & poiuytrew");
        InjectString("Release\\ProjectCS1_6.pdb");
        InjectString("Bunny Hop:");
        InjectString("Aimbot Key:");
        InjectString("##dist_color");
        InjectString("hw.dll found: 0x%llx");
        InjectString("aimbot.keyIndex");
        InjectString("aimbot.rcsy");
        InjectString("esp.boxColor");
        InjectString("menu.openKey");
        InjectString("esp.headball");
        InjectString("GameModulePtr: 0x%llX");
        InjectString("a8814d90e1baf379fb26d58d8a2d5d24");
        InjectString("##box_color");
        InjectString("Hooks installed successfully!");
        InjectString("Installing hooks!!");
        InjectString("Noflash");
        InjectString("TeamLambert");
        InjectString("KERNEL32.DLL");
        InjectString("GROUNDSTRAFE STANDUP");
        InjectString("hpp-projects\\hpp-solution\\hpp-cs16");
        InjectString("maximum_lock-on_time");
        InjectString("Aimbot and triggerbot don't shoot in smokes.");
        InjectString("glRasterPos2i");
        InjectString("glListBase");
        InjectString("glPushAttrib");
        InjectString("Ijeefo!Esbhpo!wjsvt/!Cpso!jo!b!uspqjdbm!txbnq/");
        InjectString("LowerStandart\\misc.ini");
        InjectString("AppData\\Roaming\\AltFix");
        InjectString("Thanks for zerrocxste, nrthn");
        InjectString("Build: Jun 17 2021");
        InjectString("off-screen = false");
        InjectString(".player.distance = 1");
        InjectString("|knifebot.backtrack");
        InjectString("DistanceESP = %i");
        InjectString("BunnyHopKey =");
        InjectString("LTFXSpeedKey");
        InjectString("RussianDuckKey");
        InjectString("BoxESP = %i");
        InjectString("DrawFOV = %i");
        InjectString("PanicKey = %s");
        InjectString("WallHack = %i");
        InjectString("\\VisualHack v2.ini");
        InjectString("\\VisualHack v3.ini");
        InjectString("PreS_DynamicSound: not found");
        InjectString("glDepthFunc");
        InjectString("URLDownloadToFileA");
        InjectString("Release\\Imaginary_v");
        InjectString("\\unknown-model\\");
        InjectString("knifeaim");
        InjectString("norecoil");
        InjectString("nospread");
        InjectString("kb_dist_left: %.3f");
        InjectString("[Tkz]\"%s\" not founded.");
        InjectString("Thanks to: bF, or75");
        InjectString("_hud");
        InjectString("hide");
        InjectString("entities");
        InjectString("string");
        InjectString("GameUI.dll");
        InjectString("vgui.dll");
        InjectString("vgui2.dll");
        InjectString("(c) P4rs3fl04t");
        InjectString("www.fkn0wned.com");
        InjectString("strafe_type-speed");
        InjectString("strafe");
        InjectString("UvolenStiker");
        InjectString("CHATOBJ7_SO");
        InjectString("CHATOBJ6_SO");
        InjectString("CHATOBJ5_SO");
        InjectString("MappingFailedSti");
        InjectString("PastaNeverlose");
        InjectString("OrehusStiker");
        InjectString("LegendaStiker");
        InjectString("sxxxvfvv@");
        InjectString("AProject2");

        char msg[2048];
        sprintf(msg,
            "All strings injected successfully!\n\n"
            "Total injected strings: %d\n\n"
            "Memory sections created and populated.\n"
            "Strings are now searchable in process memory.",
            (int)g_injectedStrings.size()
        );

        MessageBoxA(nullptr, msg, "String Injector - Complete", MB_OK | MB_ICONINFORMATION);

        break;
    }
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}